global:
  scrape_interval: 1m
  scrape_timeout: 20s

scrape_configs:

  - job_name: 'node-exporters'
    static_configs:
      - targets:
          - '10.0.0.83:9100'
          - '10.0.0.82:9100'
          - '10.0.0.81:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - '10.0.0.81:8080'

  - job_name: 'elasticsearch'
    static_configs:
      - targets:
          - '10.0.0.81:9114'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.0.0.81:9090']

  - job_name: 'cognitive-deployer'
    static_configs:
      - targets:
          - '10.0.0.81:8000'
          

  - job_name: 'dynamic-response'
    static_configs:
      - targets:
          - '10.0.0.81:8001'
          
