filebeat.inputs:
  # Container logs (only for main, not node2)
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    stream: all
    processors:
      - add_docker_metadata: ~
  
  - type: log
    enabled: true
    paths:
      - /srv/dionaea/dionaea.json
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      honeypot: dionaea

output.logstash:
  hosts: ["10.0.0.81:5044"]

